import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { ArrowRight, MessageSquare, Home, Users } from "lucide-react";

const ROUTES = {
  SIGNUP: "/signup",
  LOGIN: "/login",
} as const;

export default function HomePage() {
  return (
    <main className="flex flex-col min-h-screen bg-background font-sans">
      {/* Skip navigation link for keyboard users */}
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-primary focus:text-primary-foreground focus:rounded"
      >
        Skip to content
      </a>

      {/* aria-label on hero section */}
      <section
        id="main-content"
        aria-label="Hero"
        className="relative w-full pt-12 pb-24 md:pt-24 md:pb-32 overflow-hidden"
      >
        <div className="max-w-7xl mx-auto px-6 md:px-12 grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          {/* Left Column: Text & CTA */}
          <div className="flex flex-col space-y-8 z-10">
            {/* replaced leading-[1.1] with a named Tailwind class */}
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-foreground leading-tight">
              Find your perfect <br className="hidden md:block" />
              <span className="text-primary">OSU roommate</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground max-w-md">
              Connect with verified Ohio State University students, find off-campus housing, and safely match with roommates who share your living habits and vibe.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 pt-4">
              {/* use ROUTES constant */}
              <Button asChild size="lg" className="rounded-full px-8 text-base shadow-lg">
                <Link href={ROUTES.SIGNUP}>
                  Create a free account
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="rounded-full px-8 text-base">
                <Link href={ROUTES.LOGIN}>
                  Log in
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              * Requires an active @osu.edu email address to sign up.
            </p>
          </div>

          {/* Right Column: Hero Image with Gradient */}
          {/* replaced h-[400px] and h-[550px] with named Tailwind classes */}
          <div className="relative w-full h-96 md:h-[550px] rounded-3xl overflow-hidden shadow-2xl border border-border">
            {/* decorative image uses alt="" and role="presentation" */}
            <Image
              src="/background.png"
              alt=""
              role="presentation"
              fill
              priority
              sizes="(max-width: 768px) 100vw, 50vw"
              className="object-cover object-center"
            />
            {/* aria-hidden on decorative gradient overlay */}
            <div
              aria-hidden="true"
              className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent pointer-events-none"
            />

            {/* replaced text-[10px] with text-xs */}
            <div className="absolute bottom-4 right-4 text-xs text-white/80 bg-black/40 px-2 py-1 rounded backdrop-blur-md">
              This image is generated by Gemini
            </div>
          </div>
        </div>
      </section>

      {/* Divider */}
      <div className="w-full h-px bg-border max-w-7xl mx-auto" />

      {/* aria-label on features section */}
      <section aria-label="Features" className="py-20 md:py-32 w-full">
        <div className="max-w-7xl mx-auto px-6 md:px-12 text-center">
          <h2 className="text-3xl md:text-4xl font-semibold mb-16 tracking-tight text-foreground">
            Everything you need for off-campus living
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-12 md:gap-8">
            {/* renamed "Vibe Check & Match" to a more professional label */}
            <div className="flex flex-col items-center text-center group">
              <div className="w-16 h-16 flex items-center justify-center rounded-2xl bg-primary/10 text-primary mb-6 transition-transform group-hover:scale-110 duration-300">
                <Users aria-hidden="true" className="w-8 h-8" />
              </div>
              <h3 className="text-xl font-medium mb-3 text-foreground">Smart Roommate Matching</h3>
              <p className="text-muted-foreground leading-relaxed">
                Browse verified student profiles. Filter by graduation year, major, and living habits like cleanliness, quiet hours, and pet preferences.
              </p>
            </div>

            <div className="flex flex-col items-center text-center group">
              <div className="w-16 h-16 flex items-center justify-center rounded-2xl bg-blue-500/10 text-blue-500 mb-6 transition-transform group-hover:scale-110 duration-300">
                <MessageSquare aria-hidden="true" className="w-8 h-8" />
              </div>
              <h3 className="text-xl font-medium mb-3 text-foreground">Secure Live Chat</h3>
              <p className="text-muted-foreground leading-relaxed">
                Once you match, connect instantly and securely to coordinate housing plans without having to exchange personal numbers prematurely.
              </p>
            </div>

            <div className="flex flex-col items-center text-center group">
              <div className="w-16 h-16 flex items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-500 mb-6 transition-transform group-hover:scale-110 duration-300">
                <Home aria-hidden="true" className="w-8 h-8" />
              </div>
              <h3 className="text-xl font-medium mb-3 text-foreground">Discover Housing</h3>
              <p className="text-muted-foreground leading-relaxed">
                Browse our comprehensive database of off-campus rentals. Sort by sector, distance to campus, bedrooms, and price.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* aria-label on CTA section */}
      <section aria-label="Call to Action" className="bg-zinc-50 dark:bg-zinc-900/50 py-24 mb-10 w-full text-center">
        <div className="max-w-3xl mx-auto px-6 flex flex-col items-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6 tracking-tight">Ready to find your living situation?</h2>
          <p className="text-lg text-muted-foreground mb-10">
            Join thousands of Buckeyes streamlining their off-campus living experience.
          </p>
          {/* use ROUTES constant */}
          <Button asChild size="lg" className="rounded-full px-12 h-14 text-lg">
            <Link href={ROUTES.SIGNUP}>
              Get Started Now
            </Link>
          </Button>
        </div>
      </section>
    </main>
  );
}

