/** Matches `housing_property_records` (see scraper/supabase_setup.sql). */
export type HousingListing = {
  id: string;
  modified_date?: string | null;
  address: string;
  listing_url: string;
  osu_id?: string | null;
  monthly_rent: string;
  move_in_date: string;
  move_out_date: string;
  lease_term: string;
  short_lease_term: boolean;
  sublease_permitted: boolean;
  security_deposit: string;
  property_owner: string;
  property_type: string;
  sector: string;
  level: string;
  city: string;
  bedrooms: number;
  full_bathrooms: number;
  half_bathrooms: number;
  max_occupancy: number;
  wheelchair_access: boolean;
  basement: boolean;
  laundry: string;
  parking: boolean;
  num_parking_spaces: number;
  offstreet_parking: boolean;
  offstreet_monthly?: string | null;
  offstreet_yearly?: string | null;
  onstreet_parking: boolean;
  onstreet_permit_required: string;
  garage_parking: boolean;
  garage_monthly?: string | null;
  garage_yearly?: string | null;
  furnished: boolean;
  fireplace: boolean;
  air_conditioning: string;
  dishwasher: boolean;
  stove: boolean;
  refrigerator: boolean;
  security_system: boolean;
  backyard: boolean;
  deck_or_porch: boolean;
  other_amenities: string;
  /** JSONB from DB: often `string[]` of image URLs; may be a single string or object. */
  main_image_url?: unknown | null;
  pet_deposit: string;
  additional_pet_rent: string;
  additional_dog_rent: string;
  additional_cat_rent: string;
  pets_allowed: boolean;
  dogs_allowed: boolean;
  cats_allowed: boolean;
  pet_deposit_refundable: boolean;
  water_included: boolean;
  electric_included: boolean;
  gas_included: boolean;
};
